name: CI Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/*'
      - '.idea/**'
  # 检查提交信息是否包含'skip ci'，如果包含则不触发工作流
  if: "!contains(github.event.head_commit.message, 'skip ci')"



jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/*.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Retrieve version
        run: |
          version=$(grep version gradle.properties | cut -d'=' -f2)
          commit_count=$(git rev-list HEAD --count)
          echo "VERSION=${version}.r${commit_count}" >> $GITHUB_ENV

      - name: Build with gradle
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: ./gradlew --no-daemon -Dorg.gradle.jvmargs=-Xmx2g -Pversion=$VERSION dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: BiliRoamingX-${{ env.VERSION }}
          path: 'build'